/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import dao.danhsachdongvatDao;
import dao.lichsukhambenhDao;
import entity.danhsachdongvat;
import entity.lichsukhambenh;
import entity.lichsutiemphong;
import java.awt.Image;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uliti.DateUliti;

/**
 *
 * @author Hieu
 */
public class pnllsbenh extends javax.swing.JPanel {

    danhsachdongvatDao dsdao;
    lichsukhambenhDao lsbdao;
    private List<danhsachdongvat> Listdsdv = new ArrayList<>();
    String tendm = null;
    private List<lichsukhambenh> Listlsb = new ArrayList<>();
    /**
     * Creates new form pnllsbenh
     */
    public pnllsbenh(String tendm) throws Exception {
        initComponents();
        this.tendm = tendm;
        dsdao = new danhsachdongvatDao();
        lsbdao = new lichsukhambenhDao();
        fillTable();
        cbbTenDv();
    }
    private void cbbTenDv(){
        cbbTenDv.removeAllItems();
        Listdsdv = dsdao.getAllDataByTenDm(tendm);
        for (danhsachdongvat object : Listdsdv) {
            cbbTenDv.addItem(object.getTendv());
        }
        cbbTenDv.setSelectedIndex(0);
    }
    private int getIdDv(){
        int id = -1;
        int index = cbbTenDv.getSelectedIndex();
        Listdsdv = dsdao.getAllDataByTenDm(tendm);
        return Listdsdv.get(index).getId();
    }
    private void displayImage(String imagePath) {
        System.out.println(imagePath);
        ImageIcon imageIcon = new ImageIcon(imagePath);
        Image image = imageIcon.getImage();
        Image scaledImage = image.getScaledInstance(lblanh.getWidth(), lblanh.getHeight(), Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(scaledImage);
        lblanh.setIcon(imageIcon);
    }
    private void fillTable(){
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblsb.getModel();
        defaultTableModel.setRowCount(0);
        Listlsb = lsbdao.getAllData(tendm);
        if(Listlsb.isEmpty()){
            System.out.println("Danh sách Trống");
            return;
        }
        for (lichsukhambenh x : Listlsb) {
            Object[] row = {
                x.getId(),
                x.getTendv(),
                x.getLoaibenh(),
                x.getNgaykhambenh(),
                x.getTinhtrangbenh(),
                x.getAnh()
            };
            defaultTableModel.addRow(row);
        }
    }
    private void setForm() throws ParseException{
        int row = -1;
        row = tblsb.getSelectedRow();
        if(row>-1){
            txtID.setText(tblsb.getValueAt(row, 0).toString());
            txtNgayKhamBenh.setDate(DateUliti.stringToDate(tblsb.getValueAt(row, 3).toString(), "yyyy-MM-dd"));
            txtLoaiBenh.setText(tblsb.getValueAt(row, 2).toString());
            txtTinhTrangBenh.setText(tblsb.getValueAt(row, 4).toString());
            String imgname = tblsb.getValueAt(row, 5).toString();
            displayImage("src/img/"+imgname);
            cbbTenDv.setSelectedItem(tblsb.getValueAt(row, 1).toString());
        }
    }
    private lichsukhambenh getForm(){
        String idstr = txtID.getText();
        int id = -1;
        if(!idstr.equals("")){
            id = Integer.parseInt(idstr);
        }
        int iddv = getIdDv();
        String loaibenh = txtLoaiBenh.getText();
        if(loaibenh.equals("")){
            JOptionPane.showMessageDialog(this, "Loại Bệnh Không Được Để Trống", "Thông Báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        Date ngaykhambenh = txtNgayKhamBenh.getDate();
        if(ngaykhambenh == null || ngaykhambenh.equals("")){
            JOptionPane.showMessageDialog(this, "Ngày Khám Bệnh Không Được Để Trống", "Thông Báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        String tinhtrang = txtTinhTrangBenh.getText();
        if(tinhtrang.equals("")){
            JOptionPane.showMessageDialog(this, "Tình Trạng Bệnh Không Được Để Trống", "Thông Báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        lichsukhambenh lsb = new lichsukhambenh(id, iddv, loaibenh, ngaykhambenh, tinhtrang);
        return lsb;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblsb = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        cbbTenDv = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLoaiBenh = new javax.swing.JTextField();
        txtNgayKhamBenh = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        txtTinhTrangBenh = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblanh = new javax.swing.JLabel();

        tblsb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblsb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên Động Vật", "Loại Bệnh", "Ngày Khám Bệnh", "Tình Trạng Bệnh", "Ảnh"
            }
        ));
        tblsb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsb);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ID:");

        txtID.setEnabled(false);

        cbbTenDv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tên Động Vật:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Loại Bệnh:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ngày Khám Bệnh:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tình Trạng Bệnh:");

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ảnh"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblanh, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(56, 56, 56))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLoaiBenh)
                                    .addComponent(txtNgayKhamBenh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTinhTrangBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbTenDv, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnMoi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel2)))
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel3)
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(115, 115, 115)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbTenDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoaiBenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgayKhamBenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtTinhTrangBenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnMoi))
                        .addGap(17, 17, 17))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        lichsukhambenh lsb = getForm();
        if (lsb == null) {
            return;
        }
        lsbdao.create(lsb);
        fillTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        lichsukhambenh lsb = getForm();
        if (lsb == null) {
            return;
        }
        lsbdao.update(lsb);
        fillTable();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        lichsukhambenh lsb = getForm();
        if (lsb == null) {
            return;
        }
        lsbdao.delete(lsb);
        fillTable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        lblanh.setIcon(null);
        txtID.setText("");
        txtNgayKhamBenh.setDate(null);
        txtLoaiBenh.setText(null);
        txtTinhTrangBenh.setText(null);
    }//GEN-LAST:event_btnMoiActionPerformed

    private void tblsbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsbMouseClicked
        try {
            // TODO add your handling code here:
            setForm();
        } catch (ParseException ex) {
            Logger.getLogger(pnllsbenh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblsbMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbTenDv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblanh;
    private javax.swing.JTable tblsb;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLoaiBenh;
    private com.toedter.calendar.JDateChooser txtNgayKhamBenh;
    private javax.swing.JTextField txtTinhTrangBenh;
    // End of variables declaration//GEN-END:variables
}
